### ISSUE TITLE
App not exiting after closing last window

### ISSUE THREAD

**Issue by Nevon** [olahol/viewdiff#2]
If I run `git diff | viewdiff` and close the window, the command doesn't exit.

Looking at the code, it looks like it's a feature, since there's an if statement checking if I'm running it in OSX, but I'm not sure why. Is there a reason for this?

**Comment by olahol** [comment]
This is from the electron boilerplate code, where it says:

```
  // On OS X it is common for applications and their menu bar
  // to stay active until the user quits explicitly with Cmd + Q
```

https://github.com/atom/electron/blob/master/docs/tutorial/quick-start.md

I don't run OS X, but I left it in as a precaution.

**Comment by Nevon** [comment]
Ah, I see. Yeah, that makes sense when the application has a menu bar where you can do things. But in this case, it's an application that you invoke from the command line, and once you've closed it, there's no purpose in having it open. I would just remove that.

**Comment by olahol** [comment]
Alright it's done in `1.0.3`, thank you :+1:
